// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZx0OmytQpInC1K_u5KmFYO2W-yWoLKDw',
    appId: '1:275271719731:web:7ab54b41d96692f57b7c46',
    messagingSenderId: '275271719731',
    projectId: 'serene-log',
    authDomain: 'serene-log.firebaseapp.com',
    storageBucket: 'serene-log.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnTUE1OG2ZXlZnnz6abxM6VTcam6Wh-Ww',
    appId: '1:275271719731:android:3e318b867ec38b757b7c46',
    messagingSenderId: '275271719731',
    projectId: 'serene-log',
    storageBucket: 'serene-log.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcGkkZUvtzqbNw-f3Uu4E789Cak8A6Z1Q',
    appId: '1:275271719731:ios:a1fdf344c47e70a67b7c46',
    messagingSenderId: '275271719731',
    projectId: 'serene-log',
    storageBucket: 'serene-log.firebasestorage.app',
    iosBundleId: 'com.serenelog.sereneLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcGkkZUvtzqbNw-f3Uu4E789Cak8A6Z1Q',
    appId: '1:275271719731:ios:a1fdf344c47e70a67b7c46',
    messagingSenderId: '275271719731',
    projectId: 'serene-log',
    storageBucket: 'serene-log.firebasestorage.app',
    iosBundleId: 'com.serenelog.sereneLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZx0OmytQpInC1K_u5KmFYO2W-yWoLKDw',
    appId: '1:275271719731:web:6e138627273641387b7c46',
    messagingSenderId: '275271719731',
    projectId: 'serene-log',
    authDomain: 'serene-log.firebaseapp.com',
    storageBucket: 'serene-log.firebasestorage.app',
  );
}
